# order expire minutes
expire_minutes: 10
# merchant id
merchant_id: '777290058118399'
# cfca file path
pfx_filepath: /home/ubuntu/Tripalocal_V1/unionpay/pem/700000000000001_acp.p12
# cfca PEM password
password: '000000'
# x509 cert path
x509_filepath: /home/ubuntu/Tripalocal_V1/unionpay/pem/verify_sign_acp.cer
# digest method
digest_method: sha1
# notify url for back notify from unionpay
backend_url_payment: https://www.tripalocal.com/unionpay_payment_callback/
backend_url_refund: https://www.tripalocal.com/unionpay_refund_callback/
# unionpay trade address
app_trans_url: https://101.231.204.80:5000/gateway/api/appTransReq.do
front_trans_url: https://101.231.204.80:5000/gateway/api/frontTransReq.do
back_trans_url: https://101.231.204.80:5000/gateway/api/backTransReq.do
card_back_trade: https://101.231.204.80:5000/gateway/api/cardTransReq.do
single_query_url: https://101.231.204.80:5000/gateway/api/queryTrans.do
batch_trans_url: https://101.231.204.80:5000/gateway/api/batchTrans.do
file_trans_url: https://101.231.204.80:9080/